### ISSUE TITLE
Easier or better deps to consider using?

### ISSUE THREAD

**Issue by NukeManDan** [paritytech/diener#26]
https://rustacean-station.org/episode/rust-1.62-1.63-1.64/ talks about cargo-add being included in cargo itself now, and it's deps that might be relevant to this repo: 
- https://crates.io/crates/toml_edit used here already, but a lot newer versions exists
- https://github.com/killercup/cargo-edit newer, at a glance seems worth a look for perhaps better/easier format preserving changes to things in toml files. 

So this issue is more of a question: can these tools help make dealing with modifying Cargo files in diener easier/better?

**Comment by bkchr** [comment]
AFAIK cargo edit is already using `toml_edit`. At least the readme of the later states this.

We can update `toml_edit`, but everything works with the current version or?

**Comment by NukeManDan** [comment]
Yeah, perhaps not worth making the issue ad things work here fine. Just thought of this tooling when they discussed it on that podcast and wanted to share.
